/* eslint-disable camelcase */
/* cSpell:disable */

// doesn't support 1.7.10 : completely different organization (no block state, no model)
export const itemMapping = {
    '1.8.8': {
        wooden_door: 'oak_door',
        fish: 'pufferfish',
        cooked_fish: 'cooked_salmon',
        dye: 'dye_black',
        potion: 'bottle_drinkable',
        skull: 'skull_char',
    },
    1.9: {
        wooden_door: 'oak_door',
        fish: 'pufferfish',
        cooked_fish: 'cooked_salmon',
        dye: 'dye_black',
        potion: 'bottle_drinkable',
        skull: 'skull_char',
        boat: 'oak_boat',
        splash_potion: 'bottle_splash',
        lingering_potion: 'bottle_lingering',
    },
    '1.10': {
        wooden_door: 'oak_door',
        fish: 'pufferfish',
        cooked_fish: 'cooked_salmon',
        dye: 'dye_black',
        potion: 'bottle_drinkable',
        skull: 'skull_char',
        boat: 'oak_boat',
        splash_potion: 'bottle_splash',
        lingering_potion: 'bottle_lingering',
    },
    '1.11.2': {
        wooden_door: 'oak_door',
        fish: 'pufferfish',
        cooked_fish: 'cooked_salmon',
        dye: 'dye_black',
        potion: 'bottle_drinkable',
        skull: 'skull_char',
        boat: 'oak_boat',
        totem_of_undying: 'totem',
        splash_potion: 'bottle_splash',
        lingering_potion: 'bottle_lingering',
    },
    1.12: {
        wooden_door: 'oak_door',
        fish: 'pufferfish',
        cooked_fish: 'cooked_salmon',
        dye: 'dye_black',
        potion: 'bottle_drinkable',
        skull: 'skull_char',
        boat: 'oak_boat',
        totem_of_undying: 'totem',
        splash_potion: 'bottle_splash',
        lingering_potion: 'bottle_lingering',
    },
    1.13: {},
};

// TODO: read the decompiled code (automatically) to generate this
export const blockMapping = {
    '1.8.8': {
        log: 'oak_log',
        planks: 'oak_planks',
        sapling: 'oak_sapling',
        leaves: 'oak_leaves',
        tallgrass: 'tall_grass',
        deadbush: 'dead_bush',
        wool: 'white_wool',
        piston_extension: 'piston',
        yellow_flower: 'dandelion',
        red_flower: 'poppy',
        double_stone_slab: 'stone_double_slab',
        stained_glass: 'white_stained_glass',
        double_wooden_slab: 'oak_double_slab',
        wooden_slab: 'oak_slab',
        stained_hardened_clay: 'white_stained_hardened_clay',
        stained_glass_pane: 'white_stained_glass_pane',
        log2: 'acacia_log',
        leaves2: 'acacia_leaves',
        carpet: 'white_carpet',
        double_plant: 'sunflower',
        double_stone_slab2: 'red_sandstone_double_slab',
        stone_slab2: 'red_sandstone_slab',
    },
    1.9: {
        log: 'oak_log',
        planks: 'oak_planks',
        sapling: 'oak_sapling',
        leaves: 'oak_leaves',
        tallgrass: 'tall_grass',
        deadbush: 'dead_bush',
        wool: 'white_wool',
        piston_extension: 'piston',
        yellow_flower: 'dandelion',
        red_flower: 'poppy',
        double_stone_slab: 'stone_double_slab',
        stained_glass: 'white_stained_glass',
        double_wooden_slab: 'oak_double_slab',
        wooden_slab: 'oak_slab',
        stained_hardened_clay: 'white_stained_hardened_clay',
        stained_glass_pane: 'white_stained_glass_pane',
        log2: 'acacia_log',
        leaves2: 'acacia_leaves',
        carpet: 'white_carpet',
        double_plant: 'sunflower',
        double_stone_slab2: 'red_sandstone_double_slab',
        stone_slab2: 'red_sandstone_slab',
    },
    '1.10': {
        log: 'oak_log',
        planks: 'oak_planks',
        sapling: 'oak_sapling',
        leaves: 'oak_leaves',
        tallgrass: 'tall_grass',
        deadbush: 'dead_bush',
        wool: 'white_wool',
        piston_extension: 'piston',
        yellow_flower: 'dandelion',
        red_flower: 'poppy',
        double_stone_slab: 'stone_double_slab',
        stained_glass: 'white_stained_glass',
        double_wooden_slab: 'oak_double_slab',
        wooden_slab: 'oak_slab',
        stained_hardened_clay: 'white_stained_hardened_clay',
        stained_glass_pane: 'white_stained_glass_pane',
        log2: 'acacia_log',
        leaves2: 'acacia_leaves',
        carpet: 'white_carpet',
        double_plant: 'sunflower',
        double_stone_slab2: 'red_sandstone_double_slab',
        stone_slab2: 'red_sandstone_slab',
    },
    '1.11.2': {
        log: 'oak_log',
        planks: 'oak_planks',
        sapling: 'oak_sapling',
        leaves: 'oak_leaves',
        tallgrass: 'tall_grass',
        deadbush: 'dead_bush',
        wool: 'white_wool',
        piston_extension: 'piston',
        yellow_flower: 'dandelion',
        red_flower: 'poppy',
        double_stone_slab: 'stone_double_slab',
        stained_glass: 'white_stained_glass',
        double_wooden_slab: 'oak_double_slab',
        wooden_slab: 'oak_slab',
        stained_hardened_clay: 'white_stained_hardened_clay',
        stained_glass_pane: 'white_stained_glass_pane',
        log2: 'acacia_log',
        leaves2: 'acacia_leaves',
        carpet: 'white_carpet',
        double_plant: 'sunflower',
        double_stone_slab2: 'red_sandstone_double_slab',
        stone_slab2: 'red_sandstone_slab',
    },
    1.12: {
        log: 'oak_log',
        planks: 'oak_planks',
        sapling: 'oak_sapling',
        leaves: 'oak_leaves',
        tallgrass: 'tall_grass',
        deadbush: 'dead_bush',
        wool: 'white_wool',
        piston_extension: 'piston',
        yellow_flower: 'dandelion',
        red_flower: 'poppy',
        double_stone_slab: 'stone_double_slab',
        stained_glass: 'white_stained_glass',
        double_wooden_slab: 'oak_double_slab',
        wooden_slab: 'oak_slab',
        stained_hardened_clay: 'white_stained_hardened_clay',
        stained_glass_pane: 'white_stained_glass_pane',
        log2: 'acacia_log',
        leaves2: 'acacia_leaves',
        carpet: 'white_carpet',
        double_plant: 'sunflower',
        double_stone_slab2: 'red_sandstone_double_slab',
        stone_slab2: 'red_sandstone_slab',
    },
    1.13: {},
};
